package com.example.ui

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.data.api.GeminiAgentService
import com.example.data.buildengine.BuildReleaseEngine
import com.example.data.local.AgentTaskEntity
import com.example.data.local.AppDatabase
import com.example.data.local.BuildReleaseEntity
import com.example.data.local.ConnectorEntity
import com.example.data.local.ExtensionEntity
import com.example.data.local.MemoryEntity
import com.example.data.local.TaskStepEntity
import com.example.data.repository.AgentRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

enum class NavigationTab {
    DASHBOARD, TASKS, CONNECTORS, BUILD_RELEASE, MEMORY, SETTINGS
}

enum class AppLanguage {
    ARABIC, ENGLISH
}

data class BuildUiState(
    val isBuilding: Boolean = false,
    val buildProgress: Float = 0f,
    val currentStepLog: String = "",
    val diagnostics: List<BuildReleaseEngine.DiagnosticCheck> = emptyList(),
    val isRunningDiagnostics: Boolean = false
)

class AgentViewModel(application: Application) : AndroidViewModel(application) {

    private val repository: AgentRepository

    init {
        val database = AppDatabase.getDatabase(application)
        repository = AgentRepository(database.agentDao())
        viewModelScope.launch {
            repository.seedDefaultsIfEmpty()
        }
    }

    // UI Navigation & Language State
    private val _currentTab = MutableStateFlow(NavigationTab.DASHBOARD)
    val currentTab: StateFlow<NavigationTab> = _currentTab.asStateFlow()

    private val _language = MutableStateFlow(AppLanguage.ARABIC)
    val language: StateFlow<AppLanguage> = _language.asStateFlow()

    private val _selectedModel = MutableStateFlow("gemini-3.5-flash")
    val selectedModel: StateFlow<String> = _selectedModel.asStateFlow()

    // Database Flows
    val tasks: StateFlow<List<AgentTaskEntity>> = repository.allTasks
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val connectors: StateFlow<List<ConnectorEntity>> = repository.allConnectors
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val extensions: StateFlow<List<ExtensionEntity>> = repository.allExtensions
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val memories: StateFlow<List<MemoryEntity>> = repository.allMemories
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val buildReleases: StateFlow<List<BuildReleaseEntity>> = repository.allBuildReleases
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    // Prompt & Execution State
    private val _promptInput = MutableStateFlow("")
    val promptInput: StateFlow<String> = _promptInput.asStateFlow()

    private val _isExecutingPrompt = MutableStateFlow(false)
    val isExecutingPrompt: StateFlow<Boolean> = _isExecutingPrompt.asStateFlow()

    private val _activeTaskId = MutableStateFlow<Long?>(null)
    val activeTaskId: StateFlow<Long?> = _activeTaskId.asStateFlow()

    // Build State
    private val _buildUiState = MutableStateFlow(BuildUiState())
    val buildUiState: StateFlow<BuildUiState> = _buildUiState.asStateFlow()

    init {
        runPreflightDiagnostics()
    }

    fun selectTab(tab: NavigationTab) {
        _currentTab.value = tab
    }

    fun toggleLanguage() {
        _language.value = if (_language.value == AppLanguage.ARABIC) AppLanguage.ENGLISH else AppLanguage.ARABIC
    }

    fun setModel(model: String) {
        _selectedModel.value = model
    }

    fun updatePromptInput(input: String) {
        _promptInput.value = input
    }

    fun executeUserPrompt(promptText: String? = null) {
        val targetPrompt = promptText ?: _promptInput.value
        if (targetPrompt.isBlank() || _isExecutingPrompt.value) return

        _isExecutingPrompt.value = true
        _promptInput.value = ""

        viewModelScope.launch {
            // 1. Create initial task entry
            val isBuildRelated = targetPrompt.contains("apk", ignoreCase = true) ||
                    targetPrompt.contains("build", ignoreCase = true) ||
                    targetPrompt.contains("بناء", ignoreCase = true) ||
                    targetPrompt.contains("تطبيق", ignoreCase = true)

            val newTask = AgentTaskEntity(
                title = targetPrompt,
                titleAr = targetPrompt,
                description = "Automatic task generated by General Digital Agent Executive Engine",
                status = "IN_PROGRESS",
                category = if (isBuildRelated) "DEV_BUILD" else "EXECUTIVE",
                priority = "HIGH",
                assignedAgent = if (isBuildRelated) "Developer Build Agent" else "General Executive Agent",
                progress = 0.2f,
                reasoningLog = "Parsing goal & generating initial execution plan..."
            )

            val initialSteps = listOf(
                TaskStepEntity(
                    taskId = 0,
                    stepIndex = 1,
                    stepTitle = "Objective Analysis & Decomposition",
                    stepTitleAr = "تحليل الهدف وتفكيك المتطلبات",
                    isCompleted = true,
                    toolUsed = "Executive Reasoning Core",
                    logOutput = "Deconstructed user goal into actionable sub-goals."
                ),
                TaskStepEntity(
                    taskId = 0,
                    stepIndex = 2,
                    stepTitle = "Connector & Extension Orchestration",
                    stepTitleAr = "تنسيق الموصلات والتكملات البرمجية",
                    isCompleted = false,
                    toolUsed = "Universal Integration Layer",
                    logOutput = "Connecting with active extensions & memory vault..."
                ),
                TaskStepEntity(
                    taskId = 0,
                    stepIndex = 3,
                    stepTitle = "Gemini AI Execution & Synthesis",
                    stepTitleAr = "التنفيذ بواسطة الذكاء الاصطناعي Gemini",
                    isCompleted = false,
                    toolUsed = _selectedModel.value,
                    logOutput = "Querying model for structured response..."
                )
            )

            val taskId = repository.insertTaskWithSteps(newTask, initialSteps)
            _activeTaskId.value = taskId

            // Switch to Tasks tab to view execution
            _currentTab.value = NavigationTab.TASKS

            // 2. Query Gemini API
            val agentResponse = GeminiAgentService.executeAgentPrompt(
                prompt = targetPrompt,
                selectedModel = _selectedModel.value
            )

            // 3. Mark task completed
            val updatedTask = newTask.copy(
                id = taskId,
                status = "COMPLETED",
                progress = 1.0f,
                completedAt = System.currentTimeMillis(),
                reasoningLog = "Objective analyzed, connectors queried, and execution completed successfully.",
                outputResult = agentResponse
            )
            repository.updateTask(updatedTask)

            _isExecutingPrompt.value = false

            // Auto trigger build if user requested build
            if (isBuildRelated) {
                startBuildAndRelease(
                    versionName = "1.1.0",
                    versionCode = 2,
                    buildType = "RELEASE_APK",
                    changelog = "Auto release build generated from user prompt: $targetPrompt"
                )
            }
        }
    }

    fun toggleConnector(connectorKey: String, isEnabled: Boolean) {
        viewModelScope.launch {
            repository.toggleConnector(connectorKey, isEnabled)
        }
    }

    fun toggleExtension(extensionKey: String, isEnabled: Boolean) {
        viewModelScope.launch {
            repository.toggleExtension(extensionKey, isEnabled)
        }
    }

    fun addMemory(title: String, content: String, category: String, tags: String) {
        if (title.isBlank() || content.isBlank()) return
        viewModelScope.launch {
            repository.saveMemory(
                MemoryEntity(
                    keyTitle = title,
                    content = content,
                    category = category.ifBlank { "KNOWLEDGE" },
                    tags = tags.ifBlank { "general" }
                )
            )
        }
    }

    fun deleteMemory(id: Long) {
        viewModelScope.launch {
            repository.deleteMemory(id)
        }
    }

    fun deleteTask(taskId: Long) {
        viewModelScope.launch {
            repository.deleteTask(taskId)
        }
    }

    fun runPreflightDiagnostics() {
        viewModelScope.launch {
            _buildUiState.value = _buildUiState.value.copy(isRunningDiagnostics = true)
            val results = BuildReleaseEngine.runPreflightDiagnostics()
            _buildUiState.value = _buildUiState.value.copy(
                diagnostics = results,
                isRunningDiagnostics = false
            )
        }
    }

    fun startBuildAndRelease(
        versionName: String,
        versionCode: Int,
        buildType: String,
        changelog: String
    ) {
        if (_buildUiState.value.isBuilding) return

        viewModelScope.launch {
            _buildUiState.value = _buildUiState.value.copy(
                isBuilding = true,
                buildProgress = 0.05f,
                currentStepLog = "Initializing Android Build & Release System..."
            )

            val newRelease = BuildReleaseEngine.executeBuildAndRelease(
                versionName = versionName,
                versionCode = versionCode,
                buildType = buildType,
                changelog = changelog
            ) { stepLog, progress ->
                _buildUiState.value = _buildUiState.value.copy(
                    buildProgress = progress,
                    currentStepLog = stepLog
                )
            }

            repository.saveBuildRelease(newRelease)

            _buildUiState.value = _buildUiState.value.copy(
                isBuilding = false,
                buildProgress = 1.0f,
                currentStepLog = "Build Completed Successfully! Artifact: ${newRelease.buildType} (${newRelease.artifactSizeMb} MB)"
            )
        }
    }
}
